### ISSUE TITLE
LWSF Grant

### ISSUE THREAD

**Issue by jjalla** [FRC-1294/frc2024#186] opened 2023-12-11 22:15 UTC
https://forms.office.com/pages/responsepage.aspx?id=GpWzqH5GvUaXzy8GPWVrAR1TQ0T_2ttCtIn0NAqLsGdUOEtYNkhTU1FaMDJYU0dHRjhWMU4yUVE4RC4u

**Comment by ArvickC** [comment] 2024-01-04 04:11
Duplicate of #107

**Comment by FBurkelwsd** [comment] 2024-02-20 23:11
[Community Grants Acceptance Form 2023-2024 - Eastlake Pack of Parts Robotics.docx](https://github.com/FRC-1294/frc2024/files/14352081/Community.Grants.Acceptance.Form.2023-2024.-.Eastlake.Pack.of.Parts.Robotics.docx)
[Community Grants Evaluation Form 2023-2024.docx](https://github.com/FRC-1294/frc2024/files/14352082/Community.Grants.Evaluation.Form.2023-2024.docx)

**Closed** 2024-04-17 02:13 UTC
Labels: Executive
