### ISSUE TITLE
Research and Setup Junit5 unit tests + simulation for the 2024 repo

### ISSUE THREAD

**Issue by ArvickC** [FRC-1294/frc2024#17] opened 2023-06-27 00:06 UTC
Priority: Mid/High

**Comment by tcdoan** [comment] 2023-10-01 02:06
Spoke with @AadityaAgni and @bredisrising and Ankit's swerve simulation code written early 2023 was not found on frc2023 repo. Waiting for Ankit to push his swerve simulation code to GitHub.

**Comment by tcdoan** [comment] 2023-10-20 21:47
@TejaKoripellaUwU I am closing this task because it is a duplicate of task #91

**Closed** 2023-10-20 21:48 UTC
Labels: Software
