### ISSUE TITLE
Robot Cart & Drive Station

### ISSUE THREAD

**Issue by FBurkelwsd** [FRC-1294/frc2024#266] opened 2024-02-10 21:21 UTC

**Comment by FBurkelwsd** [comment] 2024-02-10 21:21
https://cad.onshape.com/documents/e6e526814530b6287f493f92/w/28f3ebb8da4ff0aefc9356fc

**Comment by ArvickC** [comment] 2024-02-10 21:46
Duplicate of #120 and #121

**Closed as not planned by ArvickC** 2024-02-10 21:46 UTC
